export const ATTRIBUTE_POOLS = {
    scientificNames: [
        "Fishus Questionablus",
        "Swimmus Suspiciously",
        "Aquaticus Unhingedus",
        "Scalesus Problematicus",
        "Finnus Chaoticus",
        "Glubbus Concerningus",
        "Oceanus Crackheadius",
        "Marinus Unpredictablus",
        "Deepus Seacretus",
        "Bubblus Confusedus",
        "Streamius Randomicus",
        "Torpedus Weirdius",
    ],

    types: [
        "Emotional Support Predator",
        "Anxiety-Fueled Swimmer",
        "Chaos Agent",
        "Professionally Unemployed",
        "Freelance Menace",
        "Certified Disaster",
        "Part-Time Cryptid",
        "Unlicensed Therapist",
        "Professional Overthinker",
        "Chaos Coordinator",
        "Vibe Assassin",
        "Aquatic Goblin",
    ],

    abilities: [
        ["side-eye", "tax fraud", "mild teleportation"],
        ["anxiety", "overthinking", "stress eating"],
        ["procrastination", "Netflix binge", "impulse buying"],
        ["gaslighting", "gatekeeping", "girlbossing"],
        ["selective hearing", "strategic incompetence", "weaponized confusion"],
        ["dramatic sighs", "passive aggression", "silent treatment"],
        ["terrible advice", "unsolicited opinions", "TMI sharing"],
        ["doom scrolling", "reply guy energy", "main character syndrome"],
        ["emotional damage", "existential dread", "vibes only"],
        ["chaos energy", "unhinged takes", "no sleep schedule"],
        ["bad decisions", "good intentions", "questionable morals"],
        ["retail therapy", "avoiding responsibilities", "living in denial"],
    ],

    diets: [
        "instant noodles, hopes and dreams",
        "leftover pizza, regret",
        "energy drinks, spite",
        "microwave dinners, existential dread",
        "coffee, more coffee, anxiety",
        "chips, validation, serotonin",
        "takeout, depression naps",
        "protein bars, delusion",
        "frozen meals, broken promises",
        "ramen, audacity",
        "cereal for dinner, life choices",
        "whatever's in the fridge, shame",
    ],

    experiences: [
        "3 failed relationships",
        "7 abandoned hobbies",
        "2 dropped out degrees",
        "5 unfinished projects",
        "12 unanswered emails",
        "4 career changes",
        "9 therapy sessions (stopped going)",
        "1 year on dating apps (no matches)",
        "6 New Year's resolutions (all failed)",
        "15 unread books on nightstand",
        "8 gym memberships (never used)",
        "20+ unfinished Netflix series",
    ],

    attitudes: [
        "passive aggressive",
        "aggressively passive",
        "cautiously unhinged",
        "confidently incorrect",
        "optimistically delusional",
        "tired but wired",
        "dead inside (affectionate)",
        "feral but friendly",
        "peacefully chaotic",
        "aggressively mediocre",
        "chronically online",
        "touch grass resistant",
    ],

    wifiConnectivity: [
        "2 bars",
        "1 bar (lying)",
        "connected (no internet)",
        "loading...",
        "airplane mode (forgot to turn off)",
        "public wifi (sketchy)",
        "mobile hotspot (data almost gone)",
        "ethernet cable from 2003",
        "neighbor's wifi (password: password123)",
        "5G (somehow worse than 4G)",
        "dial-up energy",
        "carrier pigeon faster",
    ],

    legalStatus: [
        "wanted in Malaysia",
        "banned from 3 countries",
        "on a watchlist (probably)",
        "outstanding parking tickets",
        "identity unclear",
        "technically not illegal",
        "diplomatic immunity (self-declared)",
        "witness protection (self-enrolled)",
        "no comment",
        "plead the fifth",
        "it's complicated",
        "ask my lawyer (don't have one)",
    ],

    pathfindingIQ: [
        "microwave plate",
        "wet napkin",
        "room temperature milk",
        "participation trophy",
        "WiFi router from 2008",
        "cardboard cutout",
        "screensaver",
        "elevator music",
        "loading screen",
        "Windows 95",
        "dial tone",
        "buffering icon",
    ],

    plotArmor: [
        "extreme",
        "protagonist energy",
        "somehow always fine",
        "divine intervention",
        "cartoon physics",
        "main character buff",
        "script immunity",
        "too stupid to die",
        "narrative necessity",
        "writer's pet",
        "cosmic luck",
        "reality bending",
    ],

    vibeToday: [
        "unbothered king",
        "feral goblin mode",
        "corporate zombie",
        "chaotic neutral",
        "trying (not really)",
        "hot mess express",
        "raw dog energy",
        "fight or flight (choosing neither)",
        "unhinged but thriving",
        "gaslight gatekeep girlboss",
        "no thoughts head empty",
        "vibing through the pain",
    ],
};
